version: '3.3'

services:
  mysql:
    image: mysql
    container_name: mercafacil_mysql
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    expose:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mynet

  postgresql:
    image: postgres
    container_name:  mercafacil_postgresql
    ports:
      - "5432:5432"
    expose:
      - "5234"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "admin"
    networks:
      - mynet

  userfy:
    build: .
    container_name: userfy
    ports:
      - "5100:5100"
    networks:
      - mynet
    env_file:
      - .env
    depends_on:
      - mysql
      - postgresql


networks:
  mynet:
    driver: bridge
