name: CI

on:
 push:
  branches: ["**"]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up Go
    uses: actions/setup-go@v2 
    with:
     go-version: 1.18
  - name: Go mod tidy
    run: cd src && go mod tidy
  - name: Test
    run: cd src && go test -v ./...